/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.chinatelecom.xjdh.bean;

/**
 * @author peter
 * 
 */
@org.codehaus.jackson.annotate.JsonIgnoreProperties(ignoreUnknown = true)
public class AlarmChartsResp {
	@org.codehaus.jackson.annotate.JsonProperty("title")
	private String title;

	public void setTitle(String title) {
		this.title = title;
	}

	public String getTitle() {
		return title;
	}

	@org.codehaus.jackson.annotate.JsonProperty("alarmChartsDataList")
	private AlarmChartsItem[] alarmChartsDataList;

	public void setAlarmchartsdatalist(AlarmChartsItem[] alarmChartsDataList) {
		this.alarmChartsDataList = alarmChartsDataList;
	}

	public AlarmChartsItem[] getAlarmChartsDataList() {
		return alarmChartsDataList;
	}

}