/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.chinatelecom.xjdh.bean;

@org.codehaus.jackson.annotate.JsonIgnoreProperties(ignoreUnknown = true)
public class AlarmResp {
	@org.codehaus.jackson.annotate.JsonProperty("alarmList")
	private AlarmItem[] alarmlist;

	public void setAlarmlist(AlarmItem[] alarmlist) {
		this.alarmlist = alarmlist;
	}

	public AlarmItem[] getAlarmlist() {
		return alarmlist;
	}

	@org.codehaus.jackson.annotate.JsonProperty("alarmCount")
	private Integer alarmcount;

	public void setAlarmcount(Integer alarmcount) {
		this.alarmcount = alarmcount;
	}

	public Integer getAlarmcount() {
		return alarmcount;
	}

}