/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.chinatelecom.xjdh.bean;

/**
 * @author peter
 * 
 */
@org.codehaus.jackson.annotate.JsonIgnoreProperties(ignoreUnknown = true)
public class ApiResponseStationList  {
	
	@org.codehaus.jackson.annotate.JsonProperty("subContentList")
	private EditQuestion[] subContentList;
	
	@org.codehaus.jackson.annotate.JsonProperty("memoList")
	private MemoList[] memoList;
	
	public MemoList[] getMemoList() {
		return memoList;
	}

	public void setMemoList(MemoList[] memoList) {
		this.memoList = memoList;
	}

	@org.codehaus.jackson.annotate.JsonProperty("substationList")
	private Station[] substationList;
	
	public Station[] getSubstationList() {
		return substationList;
	}

	public void setSubstationList(Station[] substationList) {
		this.substationList = substationList;
	}

	@org.codehaus.jackson.annotate.JsonProperty("devContentList")
	private DevQuestion[] devContentList;
	
	public DevQuestion[] getDevContentList() {
		return devContentList;
	}

	public void setDevContentList(DevQuestion[] devContentList) {
		this.devContentList = devContentList;
	}

	public EditQuestion[] getSubContentList() {
		return subContentList;
	}

	public void setSubContentList(EditQuestion[] subContentList) {
		this.subContentList = subContentList;
	}

	@org.codehaus.jackson.annotate.JsonProperty("stationList")
	private StationList[] stationList;
	
	@org.codehaus.jackson.annotate.JsonProperty("cityList")
	private City[] cityList;
	
	public City[] getCityList() {
		return cityList;
	}

	public void setCityList(City[] cityList) {
		this.cityList = cityList;
	}

	@org.codehaus.jackson.annotate.JsonProperty("applyInfoList")
	private Technology[] applyInfoList;
	
	public Technology[] getApplyInfoList() {
		return applyInfoList;
	}

	public void setApplyInfoList(Technology[] applyInfoList) {
		this.applyInfoList = applyInfoList;
	}

	@org.codehaus.jackson.annotate.JsonProperty("questionSubList")
	private Question[] questionList;
	

	public StationList[] getData() {
		return data;
	}

	public void setData(StationList[] data) {
		this.data = data;
	}
	
	@org.codehaus.jackson.annotate.JsonProperty("deviceList")
	private DeviceFault[] deviceList;

	public DeviceFault[] getDeviceList() {
		return deviceList;
	}

	public void setDeviceList(DeviceFault[] deviceList) {
		this.deviceList = deviceList;
	}

	@org.codehaus.jackson.annotate.JsonProperty("questionDevList")
	private DeviceInfo[] questionDevList;
	
	public DeviceInfo[] getQuestionDevList() {
		return questionDevList;
	}

	public void setQuestionDevList(DeviceInfo[] questionDevList) {
		this.questionDevList = questionDevList;
	}

	public DeviceInfo[] getDevicesInfoList() {
		return devicesInfoList;
	}

	public void setDevicesInfoList(DeviceInfo[] devicesInfoList) {
		this.devicesInfoList = devicesInfoList;
	}

	@org.codehaus.jackson.annotate.JsonProperty("devicesInfoList")
	private DeviceInfo[] devicesInfoList;
	
	public DeviceInfo[] getDeviceInfo() {
		return devicesInfoList;
	}

	public void setDeviceInfo(DeviceInfo[] devicesInfoList) {
		this.devicesInfoList = devicesInfoList;
	}

	@org.codehaus.jackson.annotate.JsonProperty("checkRoomList")
	private CheckCityList[] checkCityList;
	
	@org.codehaus.jackson.annotate.JsonProperty("subList")
	private CheckCityList[] subList;

	public CheckCityList[] getSubList() {
		return subList;
	}

	public void setSubList(CheckCityList[] subList) {
		this.subList = subList;
	}

	@org.codehaus.jackson.annotate.JsonProperty("checkSubList")
	private Country[] checkLocList;
	
	@org.codehaus.jackson.annotate.JsonProperty("subsList")
	private Country[] subsList;
	
	@org.codehaus.jackson.annotate.JsonProperty("roomsList")
	private RoomSubs[] roomsList;
	
	
	public RoomSubs[] getRoomsList() {
		return roomsList;
	}

	public void setRoomsList(RoomSubs[] roomsList) {
		this.roomsList = roomsList;
	}
	
	@org.codehaus.jackson.annotate.JsonProperty("roomList")
	private RoomSubs[] roomList;
	
	
	public RoomSubs[] getRoomList() {
		return roomList;
	}

	public void setRoomList(RoomSubs[] roomList) {
		this.roomList = roomList;
	}

	@org.codehaus.jackson.annotate.JsonProperty("subsDevList")
	private Country[] subsDevList;

	public Country[] getSubsDevList() {
		return subsDevList;
	}

	public void setSubsDevList(Country[] subsDevList) {
		this.subsDevList = subsDevList;
	}

	public Country[] getSubsList() {
		return subsList;
	}

	public void setSubsList(Country[] subsList) {
		this.subsList = subsList;
	}

	public Country[] getCheckLocList() {
		return checkLocList;
	}

	public void setCheckLocList(Country[] checkLocList) {
		this.checkLocList = checkLocList;
	}

	public CheckCityList[] getCheckCityList() {
		return checkCityList;
	}

	public void setCheckCityList(CheckCityList[] checkCityList) {
		this.checkCityList = checkCityList;
	}

	public Question[] getQuestionList() {
		return questionList;
	}

	public void setQuestionList(Question[] questionList) {
		this.questionList = questionList;
	}

	public StationList[] getStationLists() {
		return stationList;
	}

	public void setStationLists(StationList[] stationImg) {
		this.stationList = stationImg;
	}

	@org.codehaus.jackson.annotate.JsonProperty("filename")
	private String[] filename;

	public StationList[] getStationList() {
		return stationList;
	}

	public void setStationList(StationList[] stationList) {
		this.stationList = stationList;
	}

	public String[] getFilename() {
		return filename;
	}

	public void setFilename(String[] filename) {
		this.filename = filename;
	}

	@org.codehaus.jackson.annotate.JsonProperty("data")
	private StationList[] data;

}