/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.chinatelecom.xjdh.bean;

/**
 * @author peter
 * 
 */
@org.codehaus.jackson.annotate.JsonIgnoreProperties(ignoreUnknown = true)
public class ApiResponse {
	@org.codehaus.jackson.annotate.JsonProperty("ret")
	private Integer ret;

	public void setRet(Integer ret) {
		this.ret = ret;
	}

	public Integer getRet() {
		return ret;
	}

	@org.codehaus.jackson.annotate.JsonProperty("data")
	private String data;

	public void setData(String data) {
		this.data = data;
	}

	public String getData() {
		return data;
	}

	@org.codehaus.jackson.annotate.JsonProperty("stationimg")
	private String stationimg;

	public String getStationimg() {
		return stationimg;
	}

	public void setStationimg(String stationimg) {
		this.stationimg = stationimg;
	}

	@org.codehaus.jackson.annotate.JsonProperty("response")
	private String response;

	public String getResponse() {
		return response;
	}

	public void setResponse(String response) {
		this.response = response;
	}

	@org.codehaus.jackson.annotate.JsonProperty("mobile")
	private String mobile;

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Override
	public String toString() {
		return "ApiResponse [ret=" + ret + ", data=" + data + ", stationimg=" + stationimg + ", response=" + response
				+ ", mobile=" + mobile + "]";
	}

}