/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.chinatelecom.xjdh.bean;

import android.os.Parcel;
import android.os.Parcelable;

/**
 * @author peter
 * 
 */
@org.codehaus.jackson.annotate.JsonIgnoreProperties(ignoreUnknown = true)
public class DevItem implements Parcelable {

	@org.codehaus.jackson.annotate.JsonProperty("model")
	private String model;

	public void setModel(String model) {
		this.model = model;
	}

	public String getModel() {
		return model;
	}

	@org.codehaus.jackson.annotate.JsonProperty("name")
	private String name;

	public void setName(String name) {
		this.name = name;
	}

	public String getName() {
		return name;
	}

	@org.codehaus.jackson.annotate.JsonProperty("room_id")
	private String room_id;
	
	public String getRoom_id() {
		return room_id;
	}

	public void setRoom_id(String room_id) {
		this.room_id = room_id;
	}

	@org.codehaus.jackson.annotate.JsonProperty("data_id")
	private String data_id;
	
	
	
	@org.codehaus.jackson.annotate.JsonProperty("dev_group")
	private String dev_group;


	public String getDev_group() {
		return dev_group;
	}

	public void setDev_group(String dev_group) {
		this.dev_group = dev_group;
	}

	public void setData_id(String data_id) {
		this.data_id = data_id;
	}

	public String getData_id() {
		return data_id;
	}

	@org.codehaus.jackson.annotate.JsonProperty("can_open")
	@org.codehaus.jackson.annotate.JsonIgnore
	private int can_open;

	public void setCan_open(int can_open) {
		this.can_open = can_open;
	}

	public int getCan_open() {
		return can_open;
	}

	@Override
	public int describeContents() {
		return 0;
	}

	@Override
	public void writeToParcel(Parcel out, int flags) {
		out.writeString(model);
		out.writeString(name);
		out.writeString(data_id);
		out.writeString(room_id);
		out.writeInt(can_open);
		out.writeString(dev_group);
	}

	public static final Creator<DevItem> CREATOR = new Creator<DevItem>() {
		@Override
		public DevItem[] newArray(int size) {
			return new DevItem[size];
		}

		@Override
		public DevItem createFromParcel(Parcel in) {
			return new DevItem(in);
		}
	};

	public DevItem() {
		super();
	}

	public DevItem(Parcel in) {
		model = in.readString();
		name = in.readString();
		data_id = in.readString();
		room_id = in.readString();
		can_open = in.readInt();
		dev_group= in.readString();
	}
}