/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.chinatelecom.xjdh.bean;
/**
 * @author peter
 * 
 */
@org.codehaus.jackson.annotate.JsonIgnoreProperties(ignoreUnknown = true)
public class DevModelItem {
	@org.codehaus.jackson.annotate.JsonProperty("key")
	private String key;

	public void setKey(String key) {
		this.key = key;
	}

	public String getKey() {
		return key;
	}

	@org.codehaus.jackson.annotate.JsonProperty("val")
	private String val;

	public void setVal(String val) {
		this.val = val;
	}

	public String getVal() {
		return val;
	}

}