/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.chinatelecom.xjdh.bean;
/**
 * @author peter
 * 
 */
@org.codehaus.jackson.annotate.JsonIgnoreProperties(ignoreUnknown = true)
public class LoginResponse {
	@Override
	public String toString() {
		return "LoginResponse [error=" + error + ", ret=" + ret + ", response=" + response + "]";
	}

	public LoginResponse(Integer ret, String response, String error) {
		super();
		this.error = error;
		this.ret = ret;
		this.response = response;
	}

	public LoginResponse() {
		super();
	}

	@org.codehaus.jackson.annotate.JsonProperty("error")
	private String error;

	public void setError(String error) {
		this.error = error;
	}

	public String getError() {
		return error;
	}

	@org.codehaus.jackson.annotate.JsonProperty("ret")
	private Integer ret;

	public void setRet(Integer ret) {
		this.ret = ret;
	}

	public Integer getRet() {
		return ret;
	}

	@org.codehaus.jackson.annotate.JsonProperty("response")
	private String response;

	public void setResponse(String response) {
		this.response = response;
	}

	public String getResponse() {
		return response;
	}

}