/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.chinatelecom.xjdh.bean;
/**
 * @author peter
 * 
 */
@org.codehaus.jackson.annotate.JsonIgnoreProperties(ignoreUnknown = true)
public class OauthRespose {
	@org.codehaus.jackson.annotate.JsonProperty("refresh_token")
	private String refresh_token;

	public void setRefresh_token(String refresh_token) {
		this.refresh_token = refresh_token;
	}

	public String getRefresh_token() {
		return refresh_token;
	}

	@org.codehaus.jackson.annotate.JsonProperty("token_type")
	private String token_type;

	public void setToken_type(String token_type) {
		this.token_type = token_type;
	}

	public String getToken_type() {
		return token_type;
	}

	@org.codehaus.jackson.annotate.JsonProperty("expires_in")
	private Integer expires_in;

	public void setExpires_in(Integer expires_in) {
		this.expires_in = expires_in;
	}

	public Integer getExpires_in() {
		return expires_in;
	}

	@org.codehaus.jackson.annotate.JsonProperty("access_token")
	private String access_token;

	public void setAccess_token(String access_token) {
		this.access_token = access_token;
	}

	public String getAccess_token() {
		return access_token;
	}

	@org.codehaus.jackson.annotate.JsonProperty("expires")
	private Integer expires;

	public void setExpires(Integer expires) {
		this.expires = expires;
	}

	public Integer getExpires() {
		return expires;
	}

	@Override
	public String toString() {
		return "OauthRespose [refresh_token=" + refresh_token + ", token_type=" + token_type + ", expires_in="
				+ expires_in + ", access_token=" + access_token + ", expires=" + expires + "]";
	}

}