/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.chinatelecom.xjdh.bean;

import java.io.Serializable;

@org.codehaus.jackson.annotate.JsonIgnoreProperties(ignoreUnknown = true)
public class StationList implements Serializable {
	private static final long serialVersionUID = -4214630338877351418L;
	@org.codehaus.jackson.annotate.JsonProperty("id")
	private Integer id;

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getId() {
		return id;
	}

	@org.codehaus.jackson.annotate.JsonProperty("stationImage") // 图片
	private String stationImage;

	public String getStationImage() {
		return stationImage;
	}

	public void setStationImage(String stationImage) {
		this.stationImage = stationImage;
	}

	@org.codehaus.jackson.annotate.JsonProperty("name") // 局站名称
	private String name;

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@org.codehaus.jackson.annotate.JsonProperty("lng") // 经度
	private Double lng;

	public Double getLng() {
		return lng;
	}

	public void setLng(Double lng) {
		this.lng = lng;
	}

	@org.codehaus.jackson.annotate.JsonProperty("lat") // 纬度
	private Double lat;

	public Double getLat() {
		return lat;
	}

	public void setLat(Double lat) {
		this.lat = lat;
	}

	@org.codehaus.jackson.annotate.JsonProperty("newGrouping") // 新建分组名称
	private String newGrouping;

	public String getNewGrouping() {
		return newGrouping;
	}

	public void setNewGrouping(String newGrouping) {
		this.newGrouping = newGrouping;
	}
	@org.codehaus.jackson.annotate.JsonProperty("substation_id") // 局站ID
	private String substation_id;

	public String getSubstation_id() {
		return substation_id;
	}

	public void setSubstation_id(String substation_id) {
		this.substation_id = substation_id;
	}

	@Override
	public String toString() {
		return name;
	}

}