/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.chinatelecom.xjdh.bean;

import java.util.Arrays;

import android.os.Parcel;
import android.os.Parcelable;

/**
 * @author peter
 * 
 */
@org.codehaus.jackson.annotate.JsonIgnoreProperties(ignoreUnknown = true)
public class SubstationItem implements Parcelable {
	@org.codehaus.jackson.annotate.JsonProperty("roomList")
	private RoomItem[] roomlist;

	public void setRoomlist(RoomItem[] roomlist) {
		this.roomlist = roomlist;
	}

	public RoomItem[] getRoomlist() {
		return roomlist;
	}

	
	@org.codehaus.jackson.annotate.JsonProperty("lat")
	private double lat;
	@org.codehaus.jackson.annotate.JsonProperty("lng")
	private double lng;
	
	


	public double getLat() {
		return lat;
	}

	public void setLat(double lat) {
		this.lat = lat;
	}

	public double getLng() {
		return lng;
	}

	public void setLng(double lng) {
		this.lng = lng;
	}


	@org.codehaus.jackson.annotate.JsonProperty("name")
	private String name;

	public void setName(String name) {
		this.name = name;
	}

	public String getName() {
		return name;
	}

	@org.codehaus.jackson.annotate.JsonProperty("code")
	private String code;

	public void setCode(String code) {
		this.code = code;
	}

	public String getCode() {
		return code;
	}

	@Override
	public int describeContents() {
		return 0;
	}

	@Override
	public void writeToParcel(Parcel out, int flags) {
		out.writeParcelableArray(roomlist, flags);
		out.writeString(code);
		out.writeString(name);
		out.writeDouble(lat);
		out.writeDouble(lng);
	}

	public static final Creator<SubstationItem> CREATOR = new Creator<SubstationItem>() {
		@Override
		public SubstationItem[] newArray(int size) {
			return new SubstationItem[size];
		}

		@Override
		public SubstationItem createFromParcel(Parcel in) {
			return new SubstationItem(in);
		}
	};

	public SubstationItem(Parcel in) {
		Parcelable[] parcelables = in.readParcelableArray(RoomItem.class.getClassLoader());
		if (parcelables != null) {
			roomlist = Arrays.copyOf(parcelables, parcelables.length, RoomItem[].class);
		}
		code = in.readString();
		name = in.readString();
		lat = in.readDouble();
		lng = in.readDouble();
	}

	public SubstationItem() {
		roomlist = new RoomItem[0];
		code = "";
		name = "";
		lat = 0;
		lat = 0;
	}

	@Override
	public String toString() {
		return "SubstationItem [roomlist=" + Arrays.toString(roomlist) + ", lat=" + lat + ", lng=" + lng + ", name="
				+ name + ", code=" + code + "]";
	}

	
	
	

}