/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.chinatelecom.xjdh.bean;

import java.io.Serializable;
/**
 * @author peter
 * 
 */
@org.codehaus.jackson.annotate.JsonIgnoreProperties(ignoreUnknown = true)
public class UserInfo implements Serializable {

	private static final long serialVersionUID = 7220925282557754987L;
	@org.codehaus.jackson.annotate.JsonProperty("id")
	private Integer id;

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getId() {
		return id;
	}

	@org.codehaus.jackson.annotate.JsonProperty("mobile")
	private String mobile;

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getMobile() {
		return mobile;
	}

	@org.codehaus.jackson.annotate.JsonProperty("username")
	private String username;

	public void setUsername(String username) {
		this.username = username;
	}

	public String getUsername() {
		return username;
	}

	@org.codehaus.jackson.annotate.JsonProperty("info")
	private String info;

	public void setInfo(String info) {
		this.info = info;
	}

	public String getInfo() {
		return info;
	}

	@org.codehaus.jackson.annotate.JsonProperty("email")
	private String email;

	public void setEmail(String email) {
		this.email = email;
	}

	public String getEmail() {
		return email;
	}

	@org.codehaus.jackson.annotate.JsonProperty("substation_id")
	private Integer substation_id;

	public void setSubstation_id(Integer substation_id) {
		this.substation_id = substation_id;
	}

	public Integer getSubstation_id() {
		return substation_id;
	}

	@org.codehaus.jackson.annotate.JsonProperty("added_datetime")
	private String added_datetime;

	public void setAdded_datetime(String added_datetime) {
		this.added_datetime = added_datetime;
	}

	public String getAdded_datetime() {
		return added_datetime;
	}

	@org.codehaus.jackson.annotate.JsonProperty("full_name")
	private String full_name;

	public void setFull_name(String full_name) {
		this.full_name = full_name;
	}

	public String getFull_name() {
		return full_name;
	}

	@org.codehaus.jackson.annotate.JsonProperty("user_role")
	private String user_role;

	public void setUser_role(String user_role) {
		this.user_role = user_role;
	}

	public String getUser_role() {
		return user_role;
	}

	@org.codehaus.jackson.annotate.JsonProperty("gender")
	private String gender;

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getGender() {
		return gender;
	}

	@org.codehaus.jackson.annotate.JsonProperty("user_image")
	private String user_image;

	@org.codehaus.jackson.annotate.JsonProperty("linphone_number")
	private String LinphoneNumber;

	public void setUser_image(String user_image) {
		this.user_image = user_image;
	}

	public String getUser_image() {
		return user_image;
	}

	public String getLinphoneNumber() {
		return LinphoneNumber;
	}

	public void setLinphoneNumber(String linphoneNumber) {
		LinphoneNumber = linphoneNumber;
	}

	@Override
	public String toString() {
		return "UserInfo [id=" + id + ", mobile=" + mobile + ", username=" + username + ", info=" + info + ", email="
				+ email + ", substation_id=" + substation_id + ", added_datetime=" + added_datetime + ", full_name="
				+ full_name + ", user_role=" + user_role + ", gender=" + gender + ", user_image=" + user_image + "linphone_number=" + LinphoneNumber+"]";
	}
	
	
	
}